config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  root to: "home#show"

  resources :couches,   only: [:show]
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"

  resources :users, only: [:new, :create, :show] do
    scope module: :users do
      resources :reservations, only: [:index, :show]
      resources :profiles, only: [:show]
      resources :couches, only: [:new, :create, :show]
    end
  end


  resources :couches, only: [:show] do
    scope module: :couches do
      resources :photos, only: [:new, :create]
      resources :nights, only: [:new, :create]
    end
  end

  get "/search", to: "search/available_couches#index"
  get "/update", to: "search/available_couches#update"

  resources :reservations, only: [:create] do
    resources :messages, only: [:create]
  end

  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :confirmations, only: [:new, :create]

  namespace :api do
    namespace :v1 do
      resources :users, only: [:show]
    end
  end

  mount ActionCable.server, at: '/cable'
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, :phone_number, uniqueness: :true
  validates :phone_number, :first_name, :last_name, :email, presence: :true
  has_secure_password
  has_many :couches
  has_many :reservations
  has_one  :profile, dependent: :destroy

  def author_name
    "#{first_name.capitalize} #{last_name.capitalize.first}."
  end

end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  before_action :doorkeeper_authorize!

  def show
    render json: current_resource_owner.as_json, serializer: UserSerializer
  end

  private

  def current_resource_owner
    User.find(doorkeeper_token.resource_owner_id) if doorkeeper_token
  end
end

app/controllers/users/couch_photos_controller.rb
class Users::CouchPhotosController < ApplicationController
  def new
    @photo = CouchPhoto.new
  end

  def create
    @photo = CouchPhoto.new(photo_params)
    if @photo.save!
      redirect_to user_couch_path(current_user, @photo)
    end
  end

  def show
  end

  private

  def photo_params
    params.require(:couch_photo).permit(:title, :caption, :image)
  end
end

app/controllers/users/couches_controller.rb
class Users::CouchesController < UsersController
  before_action :verify_user, only: [:new, :create]

  def new
    @user = User.find(params[:user_id])
    @couch = Couch.new
  end

  def create
    couch = current_user.couches.new(couch_params)
    if couch.save
      flash[:success] = "Couch Created!"
      couch.geocode
      redirect_to user_couch_path(current_user, couch)
    else
      flash[:danger] = couch.errors.full_messages.join(", ")
      redirect_to new_user_couch_path(current_user, couch)
    end
  end

  def show
    @couch = current_user.couches.find(params[:id])
    @nights = @couch.nights
  end

  private

  def couch_params
    params.require(:couch).permit(:name,
      :description,
      :street_address,
      :city,
      :state,
      :zipcode,
      :host)
  end

  def verify_user
    render file: "public/404", status: 404 unless current_user && current_user.id == params["user_id"].to_i
  end
end

app/controllers/users/profiles_controller.rb
class Users::ProfilesController < ApplicationController
  def show
    @profile = Profile.find(params[:id])
  end
end

app/controllers/users/reservations_controller.rb
class Users::ReservationsController < UsersController
  before_action :verify_user, only: [:index]

  def index
    @travel_reservations = current_user.reservations
    @host_reservations = Reservation.host_reservations(current_user)
  end

  def show
    @reservation = Reservation.find(params[:id])
    @messages = @reservation.messages.by_created_at
    @message = Message.new
  end

  private

    def verify_user
      render file: "public/404", status: 404 unless current_user && current_user.id == params["user_id"].to_i
    end
end

app/controllers/users_controller.rb
require './lib/confirmation_sender'
class UsersController < ApplicationController
  before_action :verify_user, only: [:show]

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:current_user_id] = user.id
      redirect_to user_path(user)
    else
      flash[:danger] = user.errors.full_messages.join(", ")
      redirect_to new_user_path
    end
  end

  def show
  end

  private

    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :phone_number)
    end

    def verify_user
      render file: "public/404", status: 404 unless current_user && current_user.id == params["id"].to_i
    end
end

app/views/users/new.html.haml
%section.vanilla_form
  %h1 Create your Pad Crash Account
  %article
    = form_for @user do |f|
      = f.text_field :first_name, placeholder: "First Name"

      = f.text_field :last_name, placeholder: "Last Name"

      = f.text_field :email, placeholder: "Email"

      = f.telephone_field :phone_number, placeholder: "Phone Number"

      = f.password_field :password, placeholder: "Password"

      = f.password_field :password_confirmation, placeholder: "Confirm Password"

      = f.submit 'Sign Up'

app/views/users/show.html.haml
%section.dashboard
  %h1
    = "Welcome, #{current_user.first_name.capitalize}!"

  %article.main
    %section.info
      %h3
        Account Info
      %ul
        %li
          = "First Name: #{current_user.first_name}"
        %li
          = "Last Name: #{current_user.last_name}"
        %li
          = "Email: #{current_user.email}"
        %li
          = "Phone: #{current_user.phone_number}"

    %section.links
      %h3 What would you like to do?
      %ul
        %li
          = link_to('Add a Couch', new_user_couch_path(current_user, @couch))
        %li
          = link_to('Plan a Trip', root_path )
        %li
          = link_to('View Reservations', user_reservations_path(current_user) )

  %article.couches
    %h3 Couches
    %ul
      - current_user.couches.each do |couch|
        %li
          = link_to(user_couch_path(current_user, couch)) do
            = couch.name
            %br
            = "(#{couch.city})"